### ISSUE TITLE
New Tech Preview Create Survey does not allow users to create subsequent ones

### ISSUE THREAD

**Issue by tvo318** [ansible/ansible-ui#2488]
Please see: https://github.com/ansible/ansible-ui/issues/2678

**Comment by h-kataria** [comment]
@marshmalien can you please verify if this is still an issue.

**Comment by gundalow** [comment]
I've [transferred](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository) the GitHub issue into this repo. So closing this
